// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDhEblRFqoRyZIA1A1h80hOjTZgfAVj7E',
    appId: '1:999262951922:web:80439ba0e49fc2c6ca736b',
    messagingSenderId: '999262951922',
    projectId: 'nisit-trade',
    authDomain: 'nisit-trade.firebaseapp.com',
    storageBucket: 'nisit-trade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuXiZTEi7wNsaCJrg1_mGfqhMw8Qct6nQ',
    appId: '1:999262951922:android:9a84f790e8d46bccca736b',
    messagingSenderId: '999262951922',
    projectId: 'nisit-trade',
    storageBucket: 'nisit-trade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj1AcnapyxdqKrGrB-y5cXl_Twzdf2IY4',
    appId: '1:999262951922:ios:f4b030759721a208ca736b',
    messagingSenderId: '999262951922',
    projectId: 'nisit-trade',
    storageBucket: 'nisit-trade.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj1AcnapyxdqKrGrB-y5cXl_Twzdf2IY4',
    appId: '1:999262951922:ios:f4b030759721a208ca736b',
    messagingSenderId: '999262951922',
    projectId: 'nisit-trade',
    storageBucket: 'nisit-trade.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDhEblRFqoRyZIA1A1h80hOjTZgfAVj7E',
    appId: '1:999262951922:web:9c87d8cbec70d9d7ca736b',
    messagingSenderId: '999262951922',
    projectId: 'nisit-trade',
    authDomain: 'nisit-trade.firebaseapp.com',
    storageBucket: 'nisit-trade.firebasestorage.app',
  );
}
